---
- name: Installer Nginx
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Supprimer le site par defaut
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Deployer la configuration du domaine (reverse proxy)
  template:
    src: todo.conf.j2
    dest: /etc/nginx/sites-available/todo.conf
    mode: "0644"
  notify: reload nginx

- name: Activer le site
  file:
    src: /etc/nginx/sites-available/todo.conf
    dest: /etc/nginx/sites-enabled/todo.conf
    state: link
  notify: reload nginx

- name: Demarrer et activer Nginx
  service:
    name: nginx
    state: started
    enabled: true
